### ISSUE TITLE
Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by rcarauta** [erlangMS/ems-bus#2]

**Comment by evertonagilar** [comment]
Incluído os headers a seguir para solucionar:

access-control-max-age: 86400
access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
access-control-allow-origin: *
access-control-expose-headers: Cache-Control, Content-Language, Content-Type, Expires, Last-Modified, Content-Length, ems-catalog, ems_owner, ems_node
access-control-allow-headers: Accept, Accept-Language, Content-Language, Content-Type, X-ACCESS_TOKEN, Access-Control-Allow-Origin, Authorization, Origin, x-requested-with, Content-Range, Content-Disposition, Content-Description
